"""remove author

Revision ID: 467a10229d46
Revises: 53f2dfdfbcff
Create Date: 2020-06-15 14:11:37.070736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467a10229d46'
down_revision = '53f2dfdfbcff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
