"""add comments to model

Revision ID: eb19bf814cb3
Revises: 467a10229d46
Create Date: 2020-06-15 14:31:06.597550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb19bf814cb3'
down_revision = '467a10229d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogs', sa.Column('blog', sa.String(), nullable=True))
    op.add_column('blogs', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('blogs', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('post', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'date')
    op.drop_column('blogs', 'blog')
    op.drop_table('comments')
    # ### end Alembic commands ###
